# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-08 20:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='lastlog',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
